### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kavencat** [ArrowOS-Devices/android_device_xiaomi_wayne#1]
Error: /home/shiwei/aosp/out/soong/.intermediates/frameworks/base/framework-minus-apex/android_common/aligned/framework-minus-apex.jar contains class file vendor.lineage.touch.V1_0.Gesture, whose package name "vendor.lineage.touch.V1_0" is empty or not in the allow list build/soong/scripts/check_boot_jars/package_allowed_list.txt of packages allowed on the bootclasspath.

**Comment by wushuang110** [comment]
Error: /home/ws/arrow-12.0/out/soong/.intermediates/frameworks/base/framework-minus-apex/android_common/aligned/framework-minus-apex.jar contains class file vendor.lineage.touch.V1_0.Gesture, whose package name "vendor.lineage.touch.V1_0" is empty or not in the allow list build/soong/scripts/check_boot_jars/package_allowed_list.txt of packages allowed on the bootclasspath.
===========me too===========how to fix??

**Comment by iamimmanuelraj** [comment]
Wayne is not supported anymore as of now , so no support is give...this will return soon probably...this will be buildable then
